# Generated by Django 5.1.3 on 2024-11-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journaling", "0003_cognitiveexercise_meditation_problemsolvingsession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cognitiveexercise",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="journaling",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="meditation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="problemsolvingsession",
            options={"ordering": ["-scheduled_time"]},
        ),
    ]
