# Generated by Django 5.1.3 on 2024-11-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journaling", "0004_alter_cognitiveexercise_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cognitiveexercise",
            options={},
        ),
        migrations.AlterModelOptions(
            name="journaling",
            options={},
        ),
        migrations.AlterModelOptions(
            name="meditation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="problemsolvingsession",
            options={},
        ),
    ]
