# Generated by Django 5.1.3 on 2024-12-20 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journaling", "0008_rename_notes_problemsolvingsession_notes_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolvingsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
