# Generated by Django 5.1.3 on 2024-11-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gratitude", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompassionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
