# Generated by Django 5.1.3 on 2024-11-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gratitude", "0003_compassionexercise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compassionexercise",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="gratitude",
            options={"ordering": ["-created_at"]},
        ),
    ]
